print("Madlibs Terminal Virsion 1.1")
print("Made and programed by Henry Veedahl")
print("")
Noun1 = input("Pick a noun ")
Adjetive1 = input("Pick a adjective ")
PluarlNoun1 = input("Pick a plural noun ")
Adjetive2 = input("Pick a adjective ")
PluarlNoun2 = input("Pick a pluarl noun ")
Exclamation1 = input("Pick a exclamation ")
Verb1 = input("Pick a verb ")
Verb2 = input("Pick a verb ")
Noun2 = input("Pick a noun ")
Noun3 = input("Pick a noun ")
Adjetive3 = input("Pick a adjetive ")
PastTenseVerb = input("Pick a Past Tense Verb ")
Adjetive4 = input("Pick an Adjetive ")
Noun4 = input("Pick a noun ")
print("Once upon a/an", Noun1 ,"there where three little pigs. The first little pig was very", Adjetive2,", and he built a house for himself out of",PluarlNoun1,". The sencond little pig was",Adjetive2,",and he built a house of",PluarlNoun2,". But the thrid little pig was very", Adjetive3,", and he built his house out of genuine",PluarlNoun2,". Well one day a mean old wolf came along and saw the houses.",Exception,"! he said. I'll ",Verb1,"and I'll",Verb2,"and I'll blow your house down. And he blew down the first little pig's",Noun2,"and the sencond little pig's",Noun3,"The two little pigs ran to the third pig's house. Thereupon, the wolf began blowing, but he coulden't blow down the thrid little pig's",Adjetive3,"so he",PastTenseVerb,"off into the forest and the three little",Adjetive4,"pigs moved to Chicago and went into the",Noun4,"business")
